openbao:
  server:
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "raft" {
            path = "/openbao/data"
          }
          service_registration "kubernetes" {}
    replicas: 3
    dataStorage:
      enabled: true
      size: 1Gi
    ui:
      enabled: true
  image:
    tag: "2.3.1"
