openbao:
  server:
    extraEnvironmentVars:
      BAO_CLUSTER_ADDR: "http://$(HOSTNAME).openbao-internal:8201"
      BAO_API_ADDR: "http://$(POD_IP):8200"
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          api_addr = "http://POD_IP:8200"
          cluster_addr = "http://HOSTNAME.openbao-internal:8201"
          listener "tcp" {
            tls_disable = 1
            address = "0.0.0.0:8200"
            cluster_address = "0.0.0.0:8201"
          }
          storage "raft" {
            path = "/openbao/data"
            retry_join {
              leader_api_addr = "http://openbao-0.openbao-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://openbao-1.openbao-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://openbao-2.openbao-internal:8200"
            }
          }
          service_registration "kubernetes" {}
    replicas: 3
    dataStorage:
      enabled: true
      size: 1Gi
    ui:
      enabled: true
  image:
    tag: "2.3.1"
