apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: management-proxy
spec:
  type: ExternalName
  externalName: prometheus-grafana.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: management-proxy
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: management-proxy
spec:
  type: ExternalName
  externalName: openbao.openbao.svc.cluster.local
