all:
  children:
    k3s_servers:
      hosts:
        tpi2:
          ansible_host: tpi2
    k3s_ha_servers:
      hosts:
        tpi1:
          ansible_host: tpi1
        tpi3:
          ansible_host: tpi3
    k3s_agents:
      hosts:
        # agent1:
        #   ansible_host: 100.x.y.z
