---
image:
  name: ghcr.io/clevyr/cloudnativepg-timescale:16

database:
  name: market
  appUser: marketstore
  grafanaUser: grafana
  papertraderUser: papertrader

storage:
  size: 10Gi
  storageClass: longhorn-database

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 1Gi

monitoring:
  enabled: true

vault:
  secretPath: "secret/data/schwab-ddowell/timescaledb"
  papertraderSecretPath: "secret/data/schwab-ddowell/timescaledb/papertrader"
