---
image:
  name: timescale/timescaledb:2.26.1-pg16

database:
  name: market
  appUser: marketstore
  grafanaUser: grafana

storage:
  size: 10Gi
  storageClass: longhorn-database

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 1Gi

monitoring:
  enabled: true

vault:
  secretPath: "secret/data/schwab-ddowell/timescaledb"
