tailscale-operator:
  oauth:
    secretName: operator-oauth
  operatorConfig:
    defaultTags:
      - tag:k8s
    extraEnv:
      - name: TS_USERSPACE
        value: "false"
    securityContext:
      privileged: true
  proxyConfig:
    defaultProxyClass: kernel-tun
