apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: schwab-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: schwab-secrets
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: secret/data/{{ .Release.Namespace }}/discord
        property: webhook_url
