apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-victorialogs
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  victorialogs.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        uid: victorialogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://victoria-logs-victoria-logs-single-server.observability.svc.cluster.local:9428
        isDefault: false
        editable: true
        jsonData:
          derivedFields:
            - matcherType: label
              matcherRegex: trace_id
              name: TraceID
              url: "/d/trace-detail?var-traceId=${__value.raw}&from=${__from}&to=${__to}"
              urlDisplayLabel: View Trace
