apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: go-notify-subscriber
  labels:
    app: go-notify-subscriber
spec:
  selector:
    matchLabels:
      app: go-notify-subscriber
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
