image:
  registry: gitea.tailbecff0.ts.net
  repository: chalupa-tech/go-telemetry-mesh
  tag: v0.2.1

grpcPort: 9090
httpPort: 8080

mesh:
  pingInterval: "10s"
  pingTimeout: "1s"

resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 64Mi
