---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: go-paper-trader
  labels:
    app: go-paper-trader
spec:
  selector:
    matchLabels:
      app: go-paper-trader
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
