victoria-logs-single:
  server:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi

    persistentVolume:
      enabled: true
      size: 10Gi
      storageClassName: longhorn-single

    retentionPeriod: 14d
