---
schedule: "30 14 * * 1-5"
timeZone: "America/Denver"

image:
  registry: gitea.tailbecff0.ts.net
  repository: chalupa-tech/go-notify
  tag: latest

nats:
  url: "nats://nats.nats.svc.cluster.local:4222"

schwab:
  registration: "ddowell-individual"

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
