apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1
  imageName: {{ .Values.image.name }}

  storage:
    size: {{ .Values.storage.size }}
    storageClass: {{ .Values.storage.storageClass }}

  postgresql:
    shared_preload_libraries:
      - timescaledb

  bootstrap:
    initdb:
      database: {{ .Values.database.name }}
      owner: postgres
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb VERSION '2.19.3'
      postInitApplicationSQLRefs:
        secretRefs:
          - name: timescaledb-init-roles
            key: init-roles.sql
        configMapRefs:
          - name: timescaledb-init-sql
            key: schema.sql

  managed:
    roles:
      - name: {{ .Values.database.appUser }}
        ensure: present
        login: true
        passwordSecret:
          name: timescaledb-secrets
        inRoles:
          - pg_read_all_data
          - pg_write_all_data
      - name: {{ .Values.database.grafanaUser }}
        ensure: present
        login: true
        passwordSecret:
          name: timescaledb-grafana-secret
        inRoles:
          - pg_read_all_data
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: timescaledb
              labels:
                app.kubernetes.io/name: timescaledb
                app.kubernetes.io/component: database
            spec:
              type: ClusterIP

  resources:
    requests:
      cpu: {{ .Values.resources.requests.cpu }}
      memory: {{ .Values.resources.requests.memory }}
    limits:
      memory: {{ .Values.resources.limits.memory }}

  monitoring:
    enablePodMonitor: false
