---
- name: Provision Docker and Nexus Servers
  hosts: docker_nodes
  become: yes
  vars:
    # Explicitly specify to use Python 3
    ansible_python_interpreter: /usr/bin/python3

  roles:
    # Basic server hardening and util install
    - role: preflight

    # Configure users from vault
    - role: user_setup

    # Authenticate to Tailscale tailnet and set up magicDNS
    - role: tailscale_install

    # Install Docker and set up docker-compose plugin
    - role: docker_install

    # Provision Sonatype Nexus Repository OSS container
    - role: nexus_setup
