apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-schwab-auth-tailscale
  annotations:
    tailscale.com/proxy-class: kernel-tun
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ .Values.tailscale.hostname }}.tailbecff0.ts.net
  rules:
    - host: {{ .Values.tailscale.hostname }}.tailbecff0.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-schwab-auth
                port:
                  number: {{ .Values.service.port }}
