apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: schwab-auth-tls
spec:
  secretName: schwab-auth-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - schwab-auth.chalupatech.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: go-schwab-auth
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`schwab-auth.chalupatech.com`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: go-schwab-auth
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: go-schwab-auth-tls
  annotations:
    external-dns.alpha.kubernetes.io/target: "tpi2.tailbecff0.ts.net"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`schwab-auth.chalupatech.com`)
      kind: Rule
      services:
        - name: go-schwab-auth
          port: 8080
  tls:
    secretName: schwab-auth-tls
