apiVersion: v2
name: observability-wrapper
description: Wrapper chart for VictoriaMetrics K8s Stack
type: application
version: 0.3.0
appVersion: "v1.138.0"
dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.72.5
    repository: https://victoriametrics.github.io/helm-charts/
