kube-prometheus-stack:
  ## Grafana
  grafana:
    replicas: 1
    persistence:
      enabled: true
      size: 1Gi
    envFromSecret: "grafana-oidc-secret"
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        serve_from_sub_path: true
      auth:
        signout_redirect_url: "https://pi-k3s.chalupatech.com/ui"
      auth.generic_oauth:
        enabled: true
        name: OpenBao
        allow_sign_up: true
        scopes: user
        auth_url: "https://pi-k3s.chalupatech.com/ui/vault/identity/oidc/provider/default/authorize"
        token_url: "http://openbao-active.openbao.svc.cluster.local:8200/v1/identity/oidc/provider/default/token"
        api_url: "http://openbao-active.openbao.svc.cluster.local:8200/v1/identity/oidc/provider/default/userinfo"
        login_attribute_path: username
        role_attribute_path: "'Admin'"
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  ## Prometheus
  prometheus:
    prometheusSpec:
      replicas: 1  # Non-HA
      shards: 1
      retention: 10d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi  # NVMe space is cheap
      resources:
        requests:
          cpu: 100m
          memory: 512Mi  # Give it some room, but not 2GB
        limits:
          cpu: 1000m
          memory: 2Gi  # RAM is the constraint on Pi 8GB

  ## Alertmanager
  alertmanager:
    alertmanagerSpec:
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 128Mi

  ## Components
  prometheus-node-exporter:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 100m
        memory: 64Mi

  kube-state-metrics:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
