---
wg_tunnel_ip: "10.100.0.3/24"
wg_listen_port: 51821
wg_public_key: "WTmkrxYt7h/KcuLgsYSrjWAkgvX/fxlAbkEvGV8zX2I="
wg_private_key: "{{ vault_wg_private_key }}"

wg_peers:
  - name: dpi2
    public_key: "FVQoNWzYqj8Leu307nD/IDcnZcEV/3nhhFB4iWc5VHU="
    endpoint: "73.95.229.48:51821"
    allowed_ips:
      - "10.100.0.1/32"
      - "192.168.2.0/24"
    persistent_keepalive: 25

  # tpi1 initiates outbound — no endpoint needed.
  - name: tpi1
    public_key: "s+W6JBIswstz+cFErN4DbvgtSjUhXvwjh7vcjOrfwFY="
    allowed_ips:
      - "10.100.0.2/32"
      - "192.168.1.0/24"
    persistent_keepalive: 25
