apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: example-app
            path: k8s/apps/example-app
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: "{{REPO_URL}}"
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{name}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
