apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            path: k8s/platform/cert-manager
          - name: external-secrets
            path: k8s/platform/external-secrets
          - name: observability
            path: k8s/platform/observability
          - name: openbao
            path: k8s/platform/openbao
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{REPO_URL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
